aggregation: sum
allow_missing: true
clip_duration: 4.0
event_types: Video
frequency: 2.0
image:
  aggregation: single
  allow_missing: false
  batch_size: 8
  cache_all_layers: false
  cache_n_layers: 20
  device: cuda
  event_types: Image
  frequency: 0.0
  imsize: null
  infra:
    cluster: null
    conda_env: null
    cpus_per_task: 8
    folder: null
    forbid_single_item_computation: false
    gpus_per_node: 1
    job_name: null
    keep_in_ram: false
    logs: '{folder}/logs/{user}/%j'
    max_jobs: 128
    max_pickle_size_gb: null
    mem_gb: null
    min_samples_per_job: 4096
    mode: cached
    nodes: 1
    permissions: 511
    slurm_account: null
    slurm_additional_parameters: null
    slurm_constraint: null
    slurm_partition: null
    slurm_qos: null
    slurm_use_srun: false
    tasks_per_node: 1
    timeout_min: 25
    version: v5
    workdir: null
  layer_aggregation: group_mean
  layers:
  - 0.5
  - 0.75
  - 1.0
  model_name: facebook/vjepa2-vitg-fpc64-256
  name: HuggingFaceImage
  pretrained: true
  token_aggregation: mean
infra:
  cluster: null
  conda_env: null
  cpus_per_task: 10
  folder: /home/ath/tribev2-research/cache_p2_base
  forbid_single_item_computation: false
  gpus_per_node: 1
  job_name: null
  keep_in_ram: true
  logs: '{folder}/logs/{user}/%j'
  max_jobs: 1024
  max_pickle_size_gb: null
  mem_gb: null
  min_samples_per_job: 1
  mode: cached
  nodes: 1
  permissions: 511
  slurm_account: null
  slurm_additional_parameters: null
  slurm_constraint: volta32gb
  slurm_partition: scavenge
  slurm_qos: null
  slurm_use_srun: false
  tasks_per_node: 1
  timeout_min: 1440
  version: release
  workdir: null
layer_type: ''
max_imsize: null
name: HuggingFaceVideo
num_frames: null
use_audio: true
