aggregation: sum
allow_missing: true
batch_size: 4
cache_all_layers: false
cache_n_layers: 20
contextualized: true
device: cuda
event_types: Word
frequency: 2.0
infra:
  cluster: null
  conda_env: null
  cpus_per_task: 10
  folder: /home/ath/tribev2-research/cache_nullctl
  forbid_single_item_computation: false
  gpus_per_node: 1
  job_name: null
  keep_in_ram: true
  logs: '{folder}/logs/{user}/%j'
  max_jobs: 256
  max_pickle_size_gb: null
  mem_gb: null
  min_samples_per_job: 32
  mode: cached
  nodes: 1
  permissions: 511
  slurm_account: null
  slurm_additional_parameters: null
  slurm_constraint: volta32gb
  slurm_partition: scavenge
  slurm_qos: null
  slurm_use_srun: false
  tasks_per_node: 1
  timeout_min: 720
  version: release
  workdir: null
layer_aggregation: group_mean
layers:
- 0.5
- 0.75
- 1.0
model_name: meta-llama/Llama-3.2-3B
name: HuggingFaceText
pretrained: true
token_aggregation: mean
